# Generated by Django 3.1.6 on 2024-09-06 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomRegion', models.CharField(max_length=100)),
                ('chefLieu', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('idVille', models.AutoField(primary_key=True, serialize=False)),
                ('nomVille', models.CharField(max_length=100)),
                ('nomLangue', models.CharField(max_length=100)),
                ('nomGardienLangue', models.CharField(max_length=100)),
                ('prenomGardienLangue', models.CharField(max_length=100)),
                ('numTelGardien', models.CharField(max_length=20)),
                ('mailGardien', models.EmailField(blank=True, max_length=255, null=True)),
                ('nomSecretaire', models.CharField(blank=True, max_length=100, null=True)),
                ('prenomSecretaire', models.CharField(blank=True, max_length=100, null=True)),
                ('numTelSecretaire', models.CharField(blank=True, max_length=20, null=True)),
                ('mailSecretaire', models.EmailField(blank=True, max_length=255, null=True)),
                ('photoGardienPath', models.ImageField(blank=True, null=True, upload_to='imagesChefferies/gardienFoto/')),
                ('photoSecretairePath', models.CharField(blank=True, max_length=255, null=True)),
                ('qualite', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.BooleanField(null=True)),
            ],
            options={
                'db_table': 'ville',
            },
        ),
    ]
